# Faça um programa que leia algo pelo teclado e mostre na tela o seu tipo primitivo e todas as informações possivéis sobre ele.
a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaços? ', a.isspace())
print('Só tem letra maiúscula? ', a.isupper())
print('Só tem letra minúscula?', a.islower())
print('É um número? ', a.isnumeric())
print('É alfabético? ', a.isalpha())
print('É alfanumérico? ', a.isalnum())
print('Está capitalizada? ', a.istitle())